name: tests
on:
  push:
permissions:
  contents: none
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.17.2'
          check-latest: true
      - name: go test
        env:
          GO111MODULE: 'on'
        run: go test
